spring.application.name=CRMRest
spring.datasource.url=${DB_URL}
spring.datasource.username=${USERNAME}
spring.datasource.password=${PASSWORD}
server.servlet.context-path=${CONTEXT_PATH}
app.security.pass-pattern=${PASS_PATTERN}
jwt.secret=${SECRET}
jwt.expiresIn=${EXPIRE:15m}
spring.security.allowed=${ALLOWED_ORIGIN}
