spring.application.name=CRMRest
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
server.servlet.context-path=${CONTEXT_PATH}
app.security.pass-pattern=${PASS_PATTER}